### ISSUE TITLE
more ai data

### ISSUE THREAD

**Issue by youreadytogo** [steven2358/awesome-generative-ai#1]
hey thanks for this awesome repo,
could you please add some more using this source https://twitter.com/sonyatweetybird/status/1584580362339962880/photo/1
thanks

**Comment by steven2358** [comment]
Cool, thanks for this list. I will review them and add a selection to the repo.

**Comment by steven2358** [comment]
I've added quite a few of them. There's also a new section at the end now with links to lists such as the one you mentioned.

**Comment by tawantan236** [comment]
> ฉันได้เพิ่มบางส่วนแล้ว ตอนนี้ยังมีส่วนใหม่พร้อมลิงก์ไปยังรายการต่างๆ เช่นรายการที่คุณพูดถึง

**Comment by ghost** [comment]
> เฮ้ขอบคุณสำหรับ repo ที่ยอดเยี่ยมนี้ คุณช่วยกรุณาเพิ่มอีกโดยใช้แหล่งนี้[https://twitter.com/sonyatwittertybird/status/1584580362339962880/photo/1](https://twitter.com/sonyatweetybird/status/1584580362339962880/photo/1) ขอบคุณ

**Comment by ghost** [comment]
``

> เพิ่มเติมอีกครั้งแล้วยังมีส่วนใหม่พร้อมลิงก์ไปยังรายการต่างๆ เช่นรายการที่คุณพูดถึง

**Comment by ghost** [comment]
> เพิ่มเติมอีกครั้งแล้วยังมีส่วนใหม่พร้อมลิงก์ไปยังรายการต่างๆ เช่นรายการที่คุณพูดถึง

@youreadytogo

**Comment by ghost** [comment]
> 

@steven2358

**Comment by ghost** [comment]
> 

@youreadytogo

**Comment by ghost** [comment]
> รายการ

@youreadytogo

**Comment by ghost** [comment]
> > สวัสดี ขอบคุณสำหรับ repo ที่ยอดเยี่ยมนี้คุณช่วยกรุณารองรับพื้นที่แหล่งนี้[https://twitter.com/sonyatwittertybird/status/1584580362339962880/photo/1 ประสิทธิภาพสูง](https://twitter.com/sonyatweetybird/status/1584580362339962880/photo/1)

@youreadytogo

**Comment by ghost** [comment]
@steven2358 @steven2358
