### ISSUE TITLE
Generative AI book

### ISSUE THREAD

**Issue by davidADSP** [steven2358/awesome-generative-ai#5]
Hi Steven,
 
I’m the author of the O’Reilly Generative Deep Learning book. I’m writing to ask if it would be possible to include parts of your curated list of generative AI models as a list in the book, with a reference and link back to this repo?

If so, that would be fantastic – the book is due for publication in March 2023 (https://learning.oreilly.com/library/view/generative-deep-learning/9781098134174/)
 
If you could let me know as soon as possible, that would be much appreciated!
 
Thanks,
 
David

**Comment by steven2358** [comment]
Hi David, sure you can!

The list is published with a CC0-1.0 license (public domain) so you can use it as you wish.

Best,
Steven
