### ISSUE TITLE
Addition: vanna.ai

### ISSUE THREAD

**Issue by zainhoda** [steven2358/awesome-generative-ai#62]
Homepage: https://vanna.ai/
GitHub: https://github.com/vanna-ai/vanna
Research Paper: https://github.com/vanna-ai/vanna/blob/main/papers/ai-sql-accuracy-2023-08-17.md

It's actively under development. It started as a web app but recently converted to a Python package and the package hasn't been publicized yet.

**Comment by steven2358** [comment]
Added. 53cad55
